# THIS FILE IS AUTOGENERATED BY DBIx::Skinny::Schema::Loader 0.24, DO NOT EDIT DIRECTLY.

package Isucon2::DB::Schema;
use DBIx::Skinny::Schema;

install_table artist => schema {
    pk qw/id/;
    columns qw/id name/;
};

install_table order_request => schema {
    pk qw/id/;
    columns qw/id member_id/;
};

install_table stock => schema {
    pk qw/id/;
    columns qw/id variation_id seat_id order_id updated_at/;
};

install_table ticket => schema {
    pk qw/id/;
    columns qw/id name artist_id/;
};

install_table variation => schema {
    pk qw/id/;
    columns qw/id name ticket_id/;
};

1;
